---
booktitle: Proceedings of AAAI Spring Symposium on Survival Prediction - Algorithms,
  Challenges, and Applications 2021
shortname: SPACA
volume: '146'
year: '2021'
start: 2021-03-22
end: 2021-03-24
published: 2021-05-11
url: https://proceedings.mlr.press
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: SPACA-2021
month: 0
cycles: false
bibtex_editor: Greiner, Russell and Kumar, Neeraj and Gerds, Thomas Alexander and
  van der Schaar, Mihaela
editor:
- given: Russell
  family: Greiner
- given: Neeraj
  family: Kumar
- given: Thomas Alexander
  family: Gerds
- given: Mihaela
  family: Schaar
  prefix: van der
title: Proceedings of Machine Learning Research
description: |
  Proceedings of AAAI Spring Symposium on Survival Prediction - Algorithms, Challenges, and Applications 2021
    Held in Stanford University, Palo Alto (CA), USA on 22-24 March 2021

  Published as Volume 146 by the Proceedings of Machine Learning Research on 11 May 2021.

  Volume Edited by:
    Russell Greiner
    Neeraj Kumar
    Thomas Alexander Gerds
    Mihaela van der Schaar

  Series Editors:
    Neil D. Lawrence
date_str: 22--24 Mar
author:
  name: PMLR
baseurl: "/v146"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v146
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v146
email: ''
conference:
  name: Survival Prediction - Algorithms, Challenges and Applications
  url: https://spaca.weebly.com/
  location: Stanford University, Palo Alto (CA), USA
  dates:
  - 2021-03-22
  - 2021-03-23
  - 2021-03-24
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v146/SPACA-2021.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v146/SPACA-2021.bib
